import React, { useState, useRef } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface DeathModalProps {
  isOpen: boolean;
  onClose: () => void;
  onRevive: () => void;
}

const DeathModal: React.FC<DeathModalProps> = ({ isOpen, onClose, onRevive }) => {
  const [patientName, setPatientName] = useState('');
  const [showCertificate, setShowCertificate] = useState(false);
  const certificateRef = useRef<HTMLDivElement>(null);

  const handleSubmit = () => {
    if (patientName.trim()) {
      setShowCertificate(true);
    }
  };

  const handleDownloadPdf = async () => {
    if (certificateRef.current) {
      const canvas = await html2canvas(certificateRef.current, { scale: 2 });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const imgWidth = 210; // A4 width in mm
      const pageHeight = 295; // A4 height in mm
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let heightLeft = imgHeight;
      let position = 0;

      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      while (heightLeft >= 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }

      pdf.save(`Medical_Certificate_${patientName.replace(/\s+/g, '_')}.pdf`);
    }
  };

  const handleRevive = () => {
    onRevive();
    onClose();
    setPatientName('');
    setShowCertificate(false);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white p-6 rounded-lg shadow-lg max-w-2xl w-full mx-4">
        {!showCertificate ? (
          <>
            <h2 className="text-2xl font-bold mb-4 text-red-600">CRITICAL ALERT: Your soul has evaporated.</h2>
            <p className="mb-4">You are now medically unfit for work. Enter your name to receive your official diagnosis.</p>
            <input
              type="text"
              value={patientName}
              onChange={(e) => setPatientName(e.target.value)}
              placeholder="Enter Patient Name"
              className="w-full p-2 border border-gray-300 rounded mb-4"
            />
            <button
              onClick={handleSubmit}
              className="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600"
            >
              Get Diagnosis
            </button>
          </>
        ) : (
          <>
            <div ref={certificateRef} className="border border-gray-300 p-8 bg-white text-black font-serif">
              <div className="text-center mb-8">
                <h1 className="text-3xl font-bold mb-2">BOOBY MENTAL HEALTH CLINIC</h1>
                <p className="text-sm">404 Void Avenue, Silicon Valley, CA 90210</p>
                <p className="text-sm">+1-800-DONT-WORK</p>
              </div>
              <h2 className="text-xl font-bold text-center mb-6">MEDICAL CERTIFICATE FOR SICK LEAVE</h2>
              <div className="mb-6">
                <p><strong>Date:</strong> {new Date().toLocaleDateString()}</p>
                <p className="mt-4">To Whom It May Concern,</p>
                <p className="mt-2">This is to certify that <strong>{patientName}</strong> was examined by me today.</p>
                <p className="mt-2"><strong>Diagnosis:</strong> Acute Soul Depletion (ICD-10 Code: Z73.0 Burn-out).</p>
                <p className="mt-2">In my professional medical opinion, the patient is <strong>UNFIT FOR WORK</strong> due to severe allergy to productivity.</p>
                <p className="mt-2"><strong>Recommended Duration of Absence:</strong> Indefinitely (or until the patient recovers their will to live).</p>
              </div>
              <div className="mt-8">
                <p>Dr. A. I. Booby, M.D.</p>
                <p>License No: 00000000</p>
                <p className="mt-4 border-t border-black pt-2 text-center text-lg font-cursive">Signature</p>
              </div>
              <div className="mt-8 pt-4 border-t border-gray-300 text-xs text-gray-500">
                DISCLAIMER: This certificate is a joke generated by Booby Ticker. It is not a valid legal or medical document. Presenting this to your employer may result in immediate termination or laughter. Use at your own risk.
              </div>
            </div>
            <div className="mt-4 flex justify-between">
              <button
                onClick={handleDownloadPdf}
                className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
              >
                Download PDF
              </button>
              <button
                onClick={handleRevive}
                className="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600"
              >
                Revive Soul
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default DeathModal;